export const t = {
  whosWatching: "Kim izliyor?",
  addProfile: "Profil Ekle",
  addAccount: "IPTV Hesabı Ekle",
  profileName: "Profil Adı (İsteğe Bağlı)",
  serverUrl: "Sunucu Adresi (Örn: http://domain.com:8080)",
  username: "Kullanıcı Adı",
  password: "Şifre",
  cancel: "İptal",
  addAccountBtn: "Hesap Ekle",
  connecting: "Bağlanıyor...",
  invalidCreds: "Geçersiz giriş bilgileri veya sunucu adresi.",
  connectionError: "Sunucuya bağlanılamadı. Lütfen adresi kontrol edin.",
  home: "Ana Sayfa",
  liveTv: "Canlı TV",
  movies: "Filmler",
  series: "Diziler",
  search: "Arama",
  switchProfile: "Profil Değiştir",
  welcomeBack: "Tekrar Hoş Geldiniz",
  continueWatching: "İzlemeye Devam Et",
  noContinueWatching: "İzlemeye devam edeceğiniz bir içerik bulunduğunda burada görünecektir.",
  quickLinks: "Hızlı Bağlantılar",
  watchLiveTv: "📺 Canlı TV İzle",
  browseMovies: "🎬 Filmlere Göz At",
  browseSeries: "📺 Dizilere Göz At",
  searchPlaceholder: "Film veya dizi arayın...",
  searching: "Aranıyor...",
  searchingLong: "Binlerce içerik aranıyor... Lütfen bekleyin.",
  noResults: "Sonuç bulunamadı:",
  loadingEpisodes: "Bölümler Yükleniyor...",
  noEpisodes: "Bölüm bulunamadı.",
  backToResults: "← Sonuçlara Dön",
  backToSeries: "← Dizilere Dön",
  back: "Geri",
  loadingStream: "Yayın Yükleniyor...",
  failedToLoad: "Yayın yüklenemedi.",
  browserNotSupported: "Tarayıcınız bu formatı desteklemiyor.",
  loadingCategories: "Kategoriler Yükleniyor...",
  loadingChannels: "Kanallar Yükleniyor...",
  loadingMovies: "Filmler Yükleniyor...",
  loadingSeries: "Diziler Yükleniyor..."
};
